# Use an official Node runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /stock-trading/client

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages specified in package.json
RUN npm install

# Copy all other source code to the working directory
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "run", "dev"]
